Add missing sys import on python 3.6
Otherwise this failure occurs on test native_mb_python_tag:0

   File "rpmbuild/BUILD/xdoctest-0.15.4/setup.py", line 173, in native_mb_python_tag
     if sys.version_info[:2] >= (3, 8):

   UnboundLocalError: local variable 'sys' referenced before assignment